### ISSUE TITLE
Does not work with Locust 0.13.5

### ISSUE THREAD

**Issue by rn538e** [att-cloudnative-labs/swarmhub#13]
When I try to deploy this with locust 0.13.5 I get the following errors. What can we do to fix this?

[centos@ip-xx.xx.xxxx locust-dockprom]$ curl localhost:8081
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <title>Error response</title>
    </head>
    <body>
        <h1>Error response</h1>
        <p>Error code: 500</p>
        <p>Message: error generating metric output.</p>
        <p>Error code explanation: 500 - Server got itself in trouble.</p>
    </body>
</html>
 
Then when I try to look at the logs on the locust_explorer I see exceptions like this
 
[centos@ip-xx.xx.xx.xx locust-dockprom]$ docker logs 235a15d03302
----------------------------------------
Exception happened during processing of request from ('xx.xx.xx.xx', 54606)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 152, in do_GET
    output = encoder(registry)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/openmetrics/exposition.py", line 25, in generate_latest
    ['{0}="{1}"'.format(
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/openmetrics/exposition.py", line 26, in <listcomp>
    k, v.replace('\\', r'\\').replace('\n', r'\n').replace('"', r'\"'))
AttributeError: ("'NoneType' object has no attribute 'replace'", Metric(locust_requests_avg_content_length, Locust requests avg_content_length, gauge, , [Sample(name='locust_requests_avg_content_length', labels={'path': '/yyyyyyyy', 'method': 'POST'}, value=0.0, timestamp=None, exemplar=None), Sample(name='locust_requests_avg_content_length', labels={'path': '/xxxxx/yyyyyy/zzzzz', 'method': 'POST'}, value=3541.0, timestamp=None, exemplar=None), Sample(name='locust_requests_avg_content_length', labels={'path': 'Aggregated', 'method': None}, value=1769.9294231388978, timestamp=None, exemplar=None)]))
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('xx.xx.xx.xx', 54630)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 152, in do_GET
    output = encoder(registry)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/openmetrics/exposition.py", line 25, in generate_latest
    ['{0}="{1}"'.format(
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/openmetrics/exposition.py", line 26, in <listcomp>
    k, v.replace('\\', r'\\').replace('\n', r'\n').replace('"', r'\"'))
AttributeError: ("'NoneType' object has no attribute 'replace'", Metric(locust_requests_avg_content_length, Locust requests avg_content_length, gauge, , [Sample(name='locust_requests_avg_content_length', labels={'path': '/xxxxxxx', 'method': 'POST'}, value=0.0, timestamp=None, exemplar=None), Sample(name='locust_requests_avg_content_length', labels={'path': '/xxxxx/yyyyy/zzzzz', 'method': 'POST'}, value=3541.0, timestamp=None, exemplar=None), Sample(name='locust_requests_avg_content_length', labels={'path': 'Aggregated', 'method': None}, value=1769.3628773281953, timestamp=None, exemplar=None)]))
----------------------------------------
----------------------------------------

**Comment by kmhagan** [comment]
Hi @rn538e,

Thanks for the feedback! I'm not seeing any reason why the tool wouldn't work with locust 0.13.5. Your error shows you are running /usr/local/lib/python3.8. The tool should be running from a virtual environment. Try installing the locust version you are interested on in the image using the virtual environment: /opt/python/venv/bin/pip and make sure to run locust with the virtual environment activated

I installed locust 0.13.5 locally and was able to start up using the default locust.py and locust_prometheus.py files.

**Comment by rn538e** [comment]
Thank you for the swift response. I should have been a little more clear about when I get the error, I apologize.

I see that error when I try to visualize the metrics using locust-exporter+prometheus. 
[Locust-DockProm](https://github.com/dduleba/locust-dockprom) (locust-exporter) doesn't seem to like the JSON output that locust 0.3.15 generates. Locust 0.3.15 itself starts up fine and is able to generate load with no issues.

I am not sure if this is something I need to bring to you or to the locust-Dockprom developer

**Comment by kmhagan** [comment]
Oh ok, thanks for the clarification!

I think it might be an issue with locust-dockprom. The prometheus metrics generated from this tool come from https://github.com/att-cloudnative-labs/swarmhub/blob/master/services/deployer/ansible/roles/locust-deploy-test/files/locust_prometheus.py when your locustfile.py imports it. I did a very quick test and it seems to still be working, I'm not sure how locust-dockprom gets its metrics though, I haven't used it before.

```$ 
curl http://localhost:8089/metrics

locust_request_count{endpoint="/index", method="GET"} 5
locust_request_per_second{endpoint="/index"} 0.1087893239519916
locust_failed_requests{endpoint="/index", method="GET"} 5
locust_average_response{endpoint="/index", method="GET"} 3.321361541748047
locust_average_content_length{endpoint="/index", method="GET"} 0.0
locust_max_response_time{endpoint="/index", method="GET"} 4.259824752807617
locust_running{site="https://loadtestsiteexample.com"} 1
locust_workers{site="https://loadtestsiteexample.com"} 0
locust_users{site="https://loadtestsiteexample.com"} 1
locust_request_count{endpoint="/login", method="GET"} 1
locust_request_per_second{endpoint="/login"} 0.02175786479039832
locust_failed_requests{endpoint="/login", method="GET"} 1
locust_average_response{endpoint="/login", method="GET"} 88.3641242980957
locust_average_content_length{endpoint="/login", method="GET"} 0.0
locust_max_response_time{endpoint="/login", method="GET"} 88.3641242980957
locust_running{site="https://loadtestsiteexample.com"} 1
locust_workers{site="https://loadtestsiteexample.com"} 0
locust_users{site="https://loadtestsiteexample.com"} 1
locust_request_count{endpoint="/profile", method="GET"} 2
locust_request_per_second{endpoint="/profile"} 0.04351572958079664
locust_failed_requests{endpoint="/profile", method="GET"} 2
locust_average_response{endpoint="/profile", method="GET"} 47.597408294677734
locust_average_content_length{endpoint="/profile", method="GET"} 0.0
locust_max_response_time{endpoint="/profile", method="GET"} 91.83001518249512
locust_running{site="https://loadtestsiteexample.com"} 1
locust_workers{site="https://loadtestsiteexample.com"} 0
locust_users{site="https://loadtestsiteexample.com"} 1```

**Comment by rn538e** [comment]
I was able to get it to work. Looks like between locust 0.11.0 and 0.12.2 something changed in the format of the output, where there was a “null” for one of the metrics. Made a change in locust_exporter to handle that condition and it works now.
